#!/bin/sh
echo -n "Enter filename: "
read filename
echo -n "Enter database name: "
read dbname
echo -n "Enter database username : "
read dbuser
echo -n "Enter backup path: "
read dbpath
path=/home/$dbpath/$filename.sql
echo -n "Enter database user password: "
read -s dbpw
mysqldump -u $dbuser -p$dbpw "$dbname" > ${path}
if [ $? != "0" ]; then
echo "[Error]: Database backup  failed"
exit 1
else
echo "--------------------------"
echo "Database has been backed-up successfully"
echo "------------------------------"
echo " DB Info: "
echo ""
echo " DB Name: $dbname"
echo " DB User: $dbuser"
echo " DB Pass: $dbpw"
echo " DB Filename: $filename.sql"
echo " DB Path: $path"
echo "------------------------------------"
fi
